//User
export const FETCH_USERS = 'FETCH_USERS';
export const ADD_USER_BLOCK_CHAIN = 'ADD_USER_BLOCK_CHAIN';
export const CHECK_EXIST_USER_BLOCK_CHAIN = 'CHECK_EXIST_USER_BLOCK_CHAIN';
export const FIND_USER_BLOCK_CHAIN_BY_ID = 'FIND_USER_BLOCK_CHAIN_BY_ID';

//Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_DATA_MODAL = 'SET_DATA_MODAL';