//User
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const ADD_USER_BLOCK_CHAIN = 'ADD_USER_BLOCK_CHAIN';
export const CHECK_EXIST_USER_BLOCK_CHAIN = 'CHECK_EXIST_USER_BLOCK_CHAIN';
export const FIND_USER_BLOCK_CHAIN_BY_ID = 'FIND_USER_BLOCK_CHAIN_BY_ID';
export const CHECK_VALID_OF_USER_DATA = 'CHECK_VALID_OF_USER_DATA';
export const RESET_USERBLOCKCHAIN = 'RESET_USERBLOCKCHAIN';

//Water
export const FETCH_WATER_CONSUMPTIONS_SUCCESS = 'FETCH_WATER_CONSUMPTIONS_SUCCESS';
export const FETCH_WATER_CONSUMPTIONS_FAILURE = 'FETCH_WATER_CONSUMPTIONS_FAILURE';
export const FETCH_WATER_CONSUMPTION_DETAIL_SUCCESS = 'FETCH_WATER_CONSUMPTION_DETAIL_SUCCESS';
export const FETCH_WATER_CONSUMPTION_DETAIL_FAILURE = 'FETCH_WATER_CONSUMPTION_DETAIL_FAILURE';
export const ADD_WATER_CONSUMPTION_BLOCK_CHAIN = 'ADD_WATER_CONSUMPTION_BLOCK_CHAIN';
export const FIND_WATER_CONSUMPTION_BLOCK_CHAIN_BY_ID = 'FIND_WATER_CONSUMPTION_BLOCK_CHAIN_BY_ID';
export const CHECK_VALID_OF_WATER_CONSUMPTION_DATA = 'CHECK_VALID_OF_WATER_CONSUMPTION_DATA';
export const RESET_WATERBLOCKCHAIN = 'RESET_WATERBLOCKCHAIN';

export const FETCH_WATER_BUYING_SUCCESS = 'FETCH_WATER_BUYING_SUCCESS';
export const FETCH_WATER_BUYING_FAILURE = 'FETCH_WATER_BUYING_FAILURE';
export const ADD_WATER_BUYING_BLOCK_CHAIN = 'ADD_WATER_BUYING_BLOCK_CHAIN';
export const FIND_WATER_BUYING_BLOCK_CHAIN_BY_ID = 'FIND_WATER_BUYING_BLOCK_CHAIN_BY_ID';
export const CHECK_VALID_OF_WATER_BUYING_DATA = 'CHECK_VALID_OF_WATER_CONSUMPTION_DATA';
export const RESET_WATER_BUYING_BLOCKCHAIN = 'RESET_WATERBLOCKCHAIN';

export const FETCH_WATER_SELLING_SUCCESS = 'FETCH_WATER_SELLING_SUCCESS';
export const FETCH_WATER_SELLING_FAILURE = 'FETCH_WATER_SELLING_FAILURE';
export const ADD_WATER_SELLING_BLOCK_CHAIN = 'ADD_WATER_SELLING_BLOCK_CHAIN';
export const FIND_WATER_SELLING_BLOCK_CHAIN_BY_ID = 'FIND_WATER_SELLING_BLOCK_CHAIN_BY_ID';
export const CHECK_VALID_OF_WATER_SELLING_DATA = 'CHECK_VALID_OF_WATER_CONSUMPTION_DATA';
export const RESET_WATER_SELLING_BLOCKCHAIN = 'RESET_WATERBLOCKCHAIN';

//Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_DATA_MODAL = 'SET_DATA_MODAL';