//User
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const ADD_USER_BLOCK_CHAIN = 'ADD_USER_BLOCK_CHAIN';
export const CHECK_EXIST_USER_BLOCK_CHAIN = 'CHECK_EXIST_USER_BLOCK_CHAIN';
export const FIND_USER_BLOCK_CHAIN_BY_ID = 'FIND_USER_BLOCK_CHAIN_BY_ID';
export const CHECK_VALID_OF_DATA = 'CHECK_VALID_OF_DATA';
export const RESET_NEMBLOCKCHAIN = 'RESET_NEMBLOCKCHAIN';

//Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_DATA_MODAL = 'SET_DATA_MODAL';